use_frameworks!

# Uncomment this line to define a global platform for your project
# platform :osx, '10.12'

target 'PeopleApp' do
  pod 'SlouchDB', :path => '../'
end

target 'PeoplePocket' do
  pod 'SlouchDB', :path => '../'
end

target 'SlouchDB_Tests' do
  pod 'SlouchDB', :path => '../'
  pod 'Yaml', "~> 3.3.1"
end

